global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["127.0.0.1:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
